import React from 'react'

function home() {
  return (
    <div>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/OIP.jpeg" />
{/* <img src='/hands-1063442.jpg'/> */}
<div
  id="carouselBasicExample"
  class="carousel slide carousel-fade"
  data-mdb-ride="carousel"
>
 
  <div class="carousel-inner">
   
    <div class="carousel-item active">
      <img
        src="/hands-1063442.jpg"
        class="d-block w-100"
        alt="Sunset Over the City"
        style={{height:"650px"}}
      />
      <div class="carousel-caption d-none d-md-block">
        <h5 className=' bg-success text-white'>Welcome</h5>
        <p className=' bg-success text-white'>
        “A beautiful smile is the best universal welcome. It can make the day a good day easily.” 
        </p>
      </div>
    </div> 
  </div>
  
</div>
    </div>
  )
}

export default home
