import LoginPage from '@/Components/LoginPage'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by sathish" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/OIP.jpeg" />
      </Head>
      <LoginPage/>
    
    </>
  )
}
